apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-nested-routing-with-guards
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-nested-routing-with-guards
  template:
    metadata:
      labels:
        app: angular-nested-routing-with-guards
    spec:
      containers:
        - name: angular-nested-routing-with-guards
          image: deepaksorthiya/angular-nested-routing-with-guards:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: angular-nested-routing-with-guards-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: angular-nested-routing-with-guards
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
